### ISSUE TITLE
HTTP 200 response does not always have OK 

### ISSUE THREAD

**Issue by Alien-lv426** [MarianoGappa/jira-cli#1]
Thanks for creating this. The OK check looks for **HTTP/1.1 200 OK** but the OK part is not guaranteed to be there. Could the check just be for **HTTP/1.1 200** instead?

**Comment by marianogappa** [comment]
Hey @Alien-lv426! Thank you for trying this project and for creating an issue.
I've fixed this as part of https://github.com/marianogappa/jira-cli/commit/00da42881900f551e601766876ac0c9018096747

Let me know if this fixes it for you. I assume other API things might have changed in 5 years, so let me know if there are any further issues.

**Comment by marianogappa** [comment]
Should I close this as fixed?

**Comment by Alien-lv426** [comment]
Yes. Thank you.

**Comment by Alien-lv426** [comment]
It works perfectly now. Thanks again.

**Comment by marianogappa** [comment]
👍
